build.yml: Enable Static Compilation on Ubuntu CI
codedwrench/xlinkhandheldassistant pull request #54
Opened 2022-04-17 19:39 UTC by MasonT8198

2022-04-17 19:40 UTC, MasonT8198 commented
Seems to work flawlessly!

2022-04-20 09:14 UTC, codedwrench requested changes

2022-04-20 09:14 UTC, codedwrench commented on .github/workflows/build.yml
> +                   -DNCURSES_ROOT_DIR="~/home/mason/ncurses"
```suggestion
                   -DPCAP_ROOT_DIR="$HOME/libpcap" \
                   -DBOOST_ROOT="$HOME/boost" \
                   -DNCURSES_ROOT_DIR="$HOME/ncurses"
```

/home/mason/home/mason? That can't be right

2022-04-24 22:34 UTC, MasonT8198 commented
@codedwrench fixed

2022-04-25 05:42 UTC, codedwrench approved these changes

2022-04-25 05:42 UTC, merged